<?php 
class FileManager{
	
	public function getContent($fileName)
	{
		if(file_exists($fileName))
			return simplexml_load_file($fileName);
		else
			throw new Exception("File not found : ".$fileName);
	}
	
	private function createCss($name)
	{
		$fp = fopen($name,"wb");
		fwrite($fp, "/*!
 * Generated by Stati18n v0.0.1
 * ".$name."
 * Created by Florian Rotagnon
 * Licensed under MIT
 */
 ");
		return $fp;
	}
	
	public function createStati18n($xml)
	{
		$minify = ("true" == $xml->file->minified);
		
		$fps['main'] = $this->createCss($xml->file->name.'.css');
		
		foreach($xml->language->text as $text)
		{
			$id = $text['id'];
            $insertion = $text['insertion'];
			
            if("before" != $insertion && "after" != $insertion)
            {
                // Default after
                $insertion = "after";
            }

			foreach($text->translation as $translation)
			{
				
				$language = (string)$translation['lang'];
				$data = $translation[0];
				$deport = false;
				$i = 'main';
				
				if(isset($translation['deport']))
				{
					$deport = ($translation['deport'] == 'true')?true:false;

					if(!isset($fps[$language]))
					{
						$fps[$language] = $this->createCss($xml->file->name."-".$language.'.css');
					}
					
					$i = $language;
				}
				
				
				if(!$minify)
				{
					fwrite($fps[$i], "
.stati18n.".$language.".s18n-".$id.":".$insertion." {
    content: \"".$data."\";
}
");
				}
				else
				{
					fwrite($fps[$i], ".stati18n.".$language.".s18n-".$id.":".$insertion."{content:\"".$data."\";}");
				}
			
			}
		}
		
		foreach($fps as $fp)
			fclose($fp);
	}
}

/*Script start*/
if (2 !== $argc) {
    echo "Usage: php $argv[0] [name.xml]\n";
    exit(1);
}

$fm = new FileManager();

try{
	$domArr = $fm->getContent($argv[1]);
	$fm->createStati18n($domArr);	
	
	echo "Stati18n  : compilation success";
}
catch(Exception $e)
{
	echo $e->getMessage();
}

?> 