<?php 
class FileManager{
	
	public function getContent($fileName)
	{
		if(file_exists($fileName))
			return simplexml_load_file($fileName);
		else
			throw new Exception("File not found : ".$fileName);
	}
	
	private function createCss($name)
	{
		$fp = fopen($name,"wb");
		fwrite($fp, "/*!
 * Generated by Stati18n v0.0.1
 * ".$name."
 * Created by Florian Rotagnon
 * Licensed under MIT
 */
 ");
		return $fp;
	}
		
	private function getDeported($xml)
	{	
		$listDeported = null;
		foreach($xml->language->text as $text)
			foreach($text->translation as $translation)
				if(isset($translation['deport']) && $translation['deport'] == 'true')
				{
					$listDeported[(string)$translation['lang']] = true;
				}
		return $listDeported;
	}
	
	public function createStati18n($xml)
	{
		$minify = ("true" == $xml->file->minified);
		$host = $xml->host->name;
		
		$fps['main'] = $this->createCss($xml->file->name.'.css');
		
		$listDeported = $this->getDeported($xml);
		$dep = '';
		
		$fixTextMap = null;
		
		foreach($listDeported as $key => $val)
		{
			$dep .= $key." ";
		}

		if(!$minify)
		{
			fwrite($fps['main'],"
#stati18n-infos{
	content  : '".$host.' '.$dep."';
 }");
		}
		else
		{
			fwrite($fp,"#stati18n-infos{content:".$host.";}");
		}
		
		foreach($xml->language->text as $text)
		{
			$id = $text['id'];
            $insertion = $text['insertion'];
			
            if("before" != $insertion && "after" != $insertion)
            {
                $insertion = "after";
            }

			foreach($text->translation as $translation)
			{
				
				$language = (string)$translation['lang'];
				$data = $translation[0];
				$deport = false;
				$fix = false;
				$i = 'main';
				
				if(isset($translation['deport']))
				{
					$deport = ($translation['deport'] == 'true')?true:false;

					if(!isset($fps[$language]))
					{
						$fps[$language] = $this->createCss($xml->file->name."-".$language.'.css');
					}
					
					$i = $language;
				}
				
				if(isset($translation['fix']))
				{
					$fix = ($translation['fix'] == 'true')?true:false;
				}
				
				if($fix)
				{
					$fixTextMap[$language."§§".$id] = $data;
				}
				else if(!$minify)
				{
					fwrite($fps[$i], "
.stati18n.".$language.".s18n-".$id.":".$insertion." {
    content: \"".$data."\";
}
");					
				}
				else
				{
					fwrite($fps[$i], ".stati18n.".$language.".s18n-".$id.":".$insertion."{content:\"".$data."\";}");
				}
			}
		}
		
		if(!$minify)
		{
			fwrite($fps['main'], "
#stati18n-fixed-values {
    content: '");
		}
		else
		{
			fwrite($fps['main'], "#stati18n-fixed-values{content:'");
		}
		
		foreach($fixTextMap as $key => $value)
		{
			fwrite($fps['main'], $key.'§§'.$value.';;');
		}
		
		if(!$minify)
		{
			fwrite($fps['main'], "'
};");
		}
		else
		{
			fwrite($fps['main'], "'};");
		}
		
		foreach($fps as $fp)
			fclose($fp);
	}
}

/*Script start*/
if (2 !== $argc) {
    echo "Usage: php $argv[0] [name.xml]\n";
    exit(1);
}

$fm = new FileManager();

try{
	$domArr = $fm->getContent($argv[1]);
	$fm->createStati18n($domArr);	
	
	echo "Stati18n  : compilation success";
}
catch(Exception $e)
{
	echo $e->getMessage();
}

?> 